### PR TITLE
Add photos of meetup at 2020-02-11

### PR DESCRIPTION
**Pull request by Robert-Beier**

### CODE REVIEW

**Comment by fmalcher** [comment]
I thought of putting the photos under the talks folders so we already have the connection here. Does this make sense or is is better to hava a separate photos folder?

**Comment by Robert-Beier** [comment]
There could also be two talks at one event 😜but yeah. We could sort it all event-based.

Another thought: We could also just use the photo album feature of the meetup platform. What

**Comment by fmalcher** [comment]
Ah yes, didn't think of two talks at one event in particular... 😅
At any given time I'd really like to move away from meetup.com when they start to charge fees for attendees. And of course there should be a dedicated ngLeipzig web page some day, so I'd not rely on the meetup.com photo album as a first source.

However, how about
- putting photos into the meetup.com photo album
- AND collecting them here in the repo (or in our internal dropbox) so we have a file copy of them

**Comment by Robert-Beier** [comment]
Sorry for not answering. I’m on holiday 🎿

**Comment by fmalcher** [comment]
Take your time! 😎 We can discuss this later

**Comment by Robert-Beier** [comment]
Oh yeah. I remember the news by meetup about possible fees for the attendees in the future. I think it's a good idea to not rely on the meetup.com photo albums.

**Comment by Robert-Beier** [comment]
About the directory structure:
When grouping the photos and talks by events, we might as well group the community updates the same way. I'm alright with both grouping approaches:
- by event (2020-01-14, 2020-02-11)
- by type (community updates, photos, talks)

**Pull request merged**
